name: Update Scopus Metrics via Elsapy

on:
  schedule:
    - cron: '0 0 * * 0'  # weekly
  workflow_dispatch:

jobs:
  update-scopus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install elsapy==0.5.0

      - name: Run fetch script
        env:
          SCOPUS_API_KEY: ${{ secrets.SCOPUS_API_KEY }}
        run: python scripts/fetch_scopus_data.py

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add _data/*.json
          git commit -m "📊 Update Scopus metrics & publications" || echo "No changes"
          git push
