name: Fetch Scopus Metrics

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 1 AM UTC

jobs:
  fetch-scopus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pybliometrics

      - name: Run Scopus fetch script
        env:
          SCOPUS_API_KEY: ${{ secrets.SCOPUS_API_KEY }}
        run: python scripts/fetch_scopus_metrics.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _data/
          git commit -m "Update Scopus metrics [skip ci]" || echo "No changes to commit"
          git push
