name: Update Google Scholar Data

on:
  schedule:
    # Runs at 00:00 UTC every Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-scholar:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scholarly==1.7.2
        
    - name: Run scholar script
      run: python scripts/scholar_update.py
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add _data/scholar*.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update scholar data [skip ci]"
        git push
